<?php

namespace ethaniccc\Lumine\packets;

class CommandResponsePacket extends Packet {

	public string $target;
	public string $response;

	public function pid(): int {
		return self::COMMAND_RESPONSE;
	}

	public function encode(): void {
		parent::encode(); // TODO: Change the autogenerated stub
		$this->buffer->putString($this->target);
		$this->buffer->putString($this->response);
	}

	public function decode(): void {
		$this->target = $this->buffer->getString();
		$this->response = $this->buffer->getString();
	}

}